### PR TITLE
chore: 🤖 Add linting for insensitive and inconsiderate language

### LINKED ISSUE #38: Integrate Alex.js linter
We want to make sure that our documentation doesn't use an insensitive or offensive language. So it'd be great to integrate the [Alex.js](https://alexjs.com/) linter into our build process and CI tests. Alex is powered by [retext-equality](https://github.com/retextjs/retext-equality/blob/master/rules.md) so combats against language that is condescending, ableist, homophobic, gendered, racist, references self-harm and more. 

The React Native team recently implemented this. You can [follow these steps](https://twitter.com/rickhanlonii/status/1183790093770940416?s=20) and/or use their [PR for reference](https://github.com/facebook/react-native-website/commit/0c9962b4ea70df86796c00c17782d3c5a92bc20a).

### PR DESCRIPTION
**Pull request by theashraf**
- [x] integrate Alex.js linter
~~- [ ] fix linting issues~~
closes #38

### CODE REVIEW

**Comment by carolstran** [comment]
Hey @theashraf, thank you so much for doing this! This a really valuable step for improving our documentation and making the language more inclusive 🤸‍♂ 🍨 💯 

Are you planning or would you like to fix the issues? No pressure either way, I'm also happy to merge then fix. Just let me know 😊

**Comment by theashraf** [comment]
@carolstran you're welcome :heart: , I planned to fix linting issues but I prefer to merge and fix later

**Comment by carolstran** [comment]
Great! How about this @theashraf - We'll merge this PR and I'll add an `.alexignore` so the linter ignores the issues for now and it doesn't break the build (plus some of the issues flagged like `host` will be ignored permanently). Then whenever you are able to, you'll open a PR with the text fixes.

Does that sound ok? 😀

**Comment by theashraf** [comment]
@carolstran 
sounds great :+1:

**Comment by ksaaskil** [comment]
Note that our CircleCI configuration currently doesn't build forks, so @carolstran we probably should switch on "Build forked pull requests" in CircleCI configs (but without passing secrets as CircleCI master requires GH tokens).

**Comment by carolstran** [comment]
Good call @ksaaskil, I'll make a note of it!

**Comment by carolstran** [comment]
Merged, thanks again @theashraf 🎉 

I created #42 to have a note of what should be done. It wouldn't let me assign it to you automatically, so I tagged you in the description!

In the meantime, I'll work on the CircleCI config 😇

**Pull request merged**
